# Assumptions:
#   You're sitting inside something like: $GOPATH/src/github.com/google/kythe
#   `../../knative/serving` exists.

# Build all the kythe binaries
FROM openjdk as bins
COPY . /src
WORKDIR /src
RUN echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | \
    tee /etc/apt/sources.list.d/bazel.list &&  \
      curl https://bazel.build/bazel-release.pub.gpg | apt-key add -
RUN apt-get update && apt-get install -y bazel clang
RUN bazel build -c opt \
    //kythe/go/extractors/cmd/gotool \
    //kythe/go/indexer/cmd/go_indexer \
    //kythe/go/serving/tools/write_tables \
    //kythe/go/serving/tools/http_server
# Symlinks are bad, m'kay.
RUN mkdir /out && \
    cp /src/bazel-out/k8-opt/bin/kythe/go/extractors/cmd/gotool/linux_amd64_stripped/gotool /out/gotool && \
    cp /src/bazel-out/k8-opt/bin/kythe/go/indexer/cmd/go_indexer/linux_amd64_stripped/go_indexer /out/go_indexer && \
    cp /src/bazel-out/k8-opt/bin/kythe/go/serving/tools/write_tables/linux_amd64_stripped/write_tables /out/write_tables && \
    cp /src/bazel-out/k8-opt/bin/kythe/go/serving/tools/http_server/linux_amd64_stripped/http_server /out/http_server

FROM scratch
COPY --from=bins /out/gotool /out/gotool
COPY --from=bins /out/go_indexer /out/go_indexer
COPY --from=bins /out/write_tables /out/write_tables
COPY --from=bins /out/http_server /out/http_server
